server:
  port: 8089
  error:
    include-message: always
    include-binding-errors: always
    include-exception: false


springdoc:
  enable-native-support: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  jpa:
    show-sql: true
  datasource:
    url: ${DB_CONNECTION:jdbc:mysql://localhost:3306/banco?useMysqlMetadata=true&serverTimezone=America/Guayaquil&allowPublicKeyRetrieval=false}
    username: ${DB_USER:pablo}
    password: ${DB_PWD:12qwaszx}
  devtools:
    restart:
      enabled: true

  application:
    name: banktransaction

#liquibase:
#  change-log: classpath:db/changelog/db.changelog-master.yaml

hikari:
  url: ${DB_CONNECTION:jdbc:mysql://localhost:3306/banco?useMysqlMetadata=true&serverTimezone=America/Guayaquil&allowPublicKeyRetrieval=false}
  username: ${DB_USER:pablo}
  password: ${DB_PWD:12qwaszx}

logging:
  level:
    com:
      zaxxer:
        hikari: ERROR
    feign: DEBUG

